# Generated by Django 3.1.2 on 2020-10-30 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAutor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDeCompra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('ISSN', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('numeroPaginas', models.IntegerField()),
                ('editorial', models.CharField(max_length=100)),
                ('idAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libreria.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('idRoot', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('DNI', models.AutoField(primary_key=True, serialize=False)),
                ('tipoUser', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fechaDeNacimiento', models.DateField()),
                ('lugarDeNacimiento', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('correoElectronico', models.CharField(max_length=100)),
                ('temasLiterarios', models.CharField(max_length=100)),
                ('noticias', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaDeCredito',
            fields=[
                ('idTarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('numeroTarjeta', models.CharField(max_length=100)),
                ('saldo', models.FloatField()),
                ('DNI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libreria.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Retirados',
            fields=[
                ('idRetirado', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDeRetiro', models.DateTimeField(auto_now_add=True)),
                ('ISSN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libreria.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDeReserva', models.DateTimeField(auto_now_add=True)),
                ('DNI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libreria.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('ISSN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libreria.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('idEjemplar', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('ISSN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libreria.libro')),
                ('idCompra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Libreria.compra')),
                ('idReserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Libreria.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='DNI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libreria.usuario'),
        ),
    ]
