# Generated by Django 3.1.2 on 2020-10-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='DNI',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
