# Generated by Django 3.1.2 on 2020-10-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0003_auto_20201030_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoUser',
            field=models.BooleanField(),
        ),
    ]
