# Generated by Django 3.1.2 on 2020-10-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0004_auto_20201030_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoUser',
            field=models.IntegerField(),
        ),
    ]
