# Generated by Django 3.1.2 on 2020-10-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0006_auto_20201030_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetadecredito',
            name='tipo',
        ),
        migrations.AddField(
            model_name='tarjetadecredito',
            name='debito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarjetadecredito',
            name='saldo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='noticias',
            field=models.BooleanField(default=False),
        ),
    ]
