# Generated by Django 3.1.2 on 2020-10-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0002_auto_20201030_0452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retirados',
            new_name='Retirado',
        ),
    ]
